### ISSUE TITLE
Add `EverySetList` on top of `EveryDictList`

### ISSUE THREAD

**Issue by amitaibu** [Gizra/elm-all-set#2]
This will be on top of `EveryDictList` instead of `EveryDict`.

We would probably end up copy pasting the existing file, and just renaming `EveryDict` and then we'd need to cater for the List related functionality.

@rgrempel any additional pointers? @nedSaf might be interested in tackling this and being a maintainer of an elm package! (or at least I'm trying to push him into that direction 😜 )

**Comment by nedSaf** [comment]
😅  Alright, assigned myself, I'll check it out over the weekend.

**Comment by rgrempel** [comment]
Thinking this over, I suppose that this would essentially be equivalent to a list with a guarantee that all elements are unique. Plus, a fast implementation for checking whether an element is a member. 

Conceptually, it ought to be doable, since it's basically equivalent to a DictList where the values are all Tuple0's -- we're only interested in the keys. But there will probably be some interesting details!

**Comment by rgrempel** [comment]
A few more notes on implementation.

`EveryDictList` is supposed to be a drop-in replacement for `EveryDict`. Thus, in principle, I suppose one could start (as Amitai says) by copying `EverySet.elm` to `EverySetList.elm` (or something like that), and then replace all the occurrences of `EveryDict` with `EveryDictList`. In principle, that ought to compile -- and, in fact, it ought to work -- unless there's something I'm not thinking of.

Things like `insert`, `union`, `intersect` and `diff` will behave (in terms of ordering) as described in `EveryDictList`, so it would be useful to document that. (For instance, `insert` inserts the new element at the end, or, if the element was already in the set, moves it to the end).

Then, I guess it would be a question of going through the rest of the `EveryDictList` API (the parts not taken from `EveryDict`), and figuring out which functions would also belong in `EverySetList`, and implementing them according to the pattern that `EverySet` already uses (i.e. supplying `()` when a value is needed).

**Comment by rgrempel** [comment]
BTW, there is an existing package for unique lists:

http://package.elm-lang.org/packages/Chadtech/unique-list/2.0.0

However, the API is limited, compared to what building on `EveryDictList` would offer. (There are a few things in `UniqueList` that might be nice, like `isBefore`).
